spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: "tiger"
    password: "foobar"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MariaDB103Dialect


secret: "1lndsf9123kn4op9134kl1n4910xxd01"